<?xml version="1.0"?>
<package format="3">
  <name>robot_system_monitor</name>
  <version>0.0.1</version>
  <description>ROS2-based robot state acquisition, communication management and visualization system.</description>

  <maintainer email="15398575458@163.com">zixi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>diagnostic_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
